# -*- coding: utf-8 -*-
"""Documentation Semester Project Group 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1txt-5A9_QqzkbgMl29f1CFQTInHDn0vB
"""

Want to use secure shell (ssh) which provides an encrypted connection to the remote machine

PuTTY needed to use ssh from a windows computer:

https://www.putty.org/